M48
; DRILL file {KiCad 8.0.7} date 2025-01-07T13:33:49+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-01-07T13:33:49+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X3.9015Y-2.1297
X3.9015Y-5.2301
X6.992Y-2.1297
X6.992Y-5.2301
M30
